import React, { useState } from 'react';
import { useStore, getCurrentStage, getTotalXP } from '../../lib/store';
import { createCertificatePDF, generateVerificationCode } from '../../lib/certificates';
import { FileCheck, Download, ExternalLink, ShieldCheck } from 'lucide-react';
import styles from './CertificatesView.module.css';

export const CertificatesView: React.FC = () => {
  const { xpEvents, profile } = useStore();
  const xp = getTotalXP(xpEvents);
  const stage = getCurrentStage(xp);

  const [generating, setGenerating] = useState(false);
  const [issuedCode, setIssuedCode] = useState<string | null>(null);

  const handleGenerateStageCert = async () => {
    setGenerating(true);
    const code = generateVerificationCode(`stage-${stage.id}`);
    setIssuedCode(code);

    const pdfBytes = await createCertificatePDF({
      learnerName: profile.name,
      trackOrStageTitle: `Stage ${stage.id}: ${stage.name} Milestone`,
      type: 'Stage Milestone',
      dateStr: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
      verificationCode: code
    });

    // Trigger download
    const blob = new Blob([pdfBytes as any], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `CadeCodemy-Certificate-${stage.name}.pdf`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setGenerating(false);
  };

  return (
    <div className={styles.certContainer}>
      <header className={styles.header}>
        <h1>Official Certificates</h1>
        <p className={styles.lead}>
          Verifiable, high-resolution PDF credentials signed by Kabo Merapelo Onamile. Zero fees, zero paywalls.
        </p>
      </header>

      {/* Active Eligible Stage Certificate */}
      <section className={styles.certCard}>
        <div className={styles.certIconBox}>
          <FileCheck size={36} />
        </div>

        <div className={styles.certContent}>
          <div className={styles.certType}>STAGE MILESTONE CERTIFICATE</div>
          <h2>Stage {stage.id}: {stage.name}</h2>
          <p>
            Awarded for demonstrating competence up to {stage.name} level ({stage.xpNeeded.toLocaleString()} XP). Includes cryptographic verification code and QR identifier.
          </p>

          <div className={styles.metaRow}>
            <span>Recipient: <strong>{profile.name}</strong></span>
            <span>Signatory: <strong>Kabo Merapelo Onamile, Creator</strong></span>
          </div>

          <div className={styles.actionRow}>
            <button
              className={styles.downloadBtn}
              onClick={handleGenerateStageCert}
              disabled={generating}
            >
              <Download size={16} />
              <span>{generating ? 'Compiling PDF...' : 'Download Certificate (PDF)'}</span>
            </button>
          </div>

          {issuedCode && (
            <div className={styles.codeSuccessBox}>
              <ShieldCheck size={16} className={styles.shieldIcon} />
              <span>Generated Code: <code>{issuedCode}</code>. Verify on the /verify page.</span>
            </div>
          )}
        </div>
      </section>

      {/* Verification Explanation */}
      <section className={styles.verifyInfoBox}>
        <h3>Cryptographic Verification Notice</h3>
        <p>
          Every certificate generated by CadeCodemy carries a deterministic hash and QR code. You can test and inspect verification codes on the{' '}
          <a href="#/verify" className={styles.inlineLink}>
            Verification Portal <ExternalLink size={12} />
          </a>.
        </p>
      </section>
    </div>
  );
};
